exclude: |
  (?x)(
        ^docs/|
        ^econsa/morris.py|
        ^econsa/tests/test_morris.py
  )
repos:

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.7.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=100000']  # Set to max file size in Github
    -   id: check-byte-order-marker
        types: [text]
    -   id: check-merge-conflict
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
    -   id: trailing-whitespace

-   repo: https://github.com/asottile/pyupgrade
    rev: v1.24.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    - id: flake8
      files: '(\.py|wscript)$'
      additional_dependencies: [
        flake8-bugbear, flake8-builtins, flake8-comprehensions,
        flake8-deprecated, flake8-docstrings, flake8-eradicate,
        flake8-print, flake8-rst-docstrings, flake8-todo,
        flake8-type-annotations, pep8-naming, pydocstyle
      ]
      # Harmonizing flake8 and black
      args: [
        '--max-line-length=100',
        '--ignore=E203,E402,E800,W503',
        '--select=B,C,E,F,W,T4,B9'
      ]

