name: econsa

channels:
  - defaults
  - conda-forge
  - opensourceeconomics

dependencies:
  - python=3.7
  - sphinx>=1.4
  - pandas>=0.25
  - numpy=1.16
  - scipy
  - jupyter
  - seaborn
  - pytest
  - numba
  - pip=19.3.1
  - pdbpp
  - chaospy
  - pytest-black
  - pytest-flake8
  - pytest-cov
  - jupyterlab
  - nbsphinx
  - hypothesis
  - pip:
    - SALib
    # - salib==1.3.8
    - isort
    - black
    - black-nb
    - flake8-nb
    - sphinx_rtd_theme
    - nbsphinx
    - pre-commit==1.18.3
    - sphinxcontrib-bibtex
    - numpydoc
    - git+https://github.com/OpenSourceEconomics/temfpy.git
