channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - sphinx
  - pandas>=0.25
  - numpy=1.16
  - pip
  - scipy
  - jupyter
  - jupyterlab
  - seaborn
  - numba
  - chaospy
  - pytest
  - pytest-black
  - pytest-flake8
  - pytest-cov
  - pytest-sugar
  - hypothesis
  - nbsphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex

  - pip:
    - numpydoc
