name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: econsa
           environment-file: environment.yml
           python-version: 3.7
    - uses: ammaraskar/sphinx-action@master
      with:
          docs-folder: "docs/"
    - name: run tests
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        pytest
    - name: run figures
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        cd docs/_static/codes; python fig-illustrations.py
