name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: econsa
           environment-file: environment.yml
           python-version: 3.7

    - name: run tests
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        pytest --cov=econsa --cov-report=xml

        # We want to make sure proper formatting of the notebooks.
        flake8-nb; [ $? -eq 0 ] || exit 1
        black-nb .; [ $? -eq 0 ] || exit 1

        # We want to pull the submodules
        git submodule update --init --recursive

        # We want to local build of the documentation to succeed. This can be
        # removed once readthedocs.org is part of PR testing setup.
        cd docs; make html; cd $PROJECT_ROOT

    - name: upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage.xml

    - name: run figures
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc

        cd docs/_static/codes
        python fig-illustrations.py
        python fig-harris-tradeoff.py
        python fig-borgonovo-cdf.py
